document.writeln("<script type=\"text\/javascript\"><!--");
document.writeln("google_ad_client = \"pub-5637832140118238\";");
document.writeln("\/* 728x90, ´´½¨ÓÚ 08-3-13 *\/");
document.writeln("google_ad_slot = \"3537060730\";");
document.writeln("google_ad_width = 728;");
document.writeln("google_ad_height = 90;");
document.writeln("\/\/-->");
document.writeln("<\/script>");
document.writeln("<script type=\"text\/javascript\"");
document.writeln("src=\"http:\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js\">");
document.writeln("<\/script>");
