document.writeln("<!-- SiteSearch Google -->");
document.writeln("<form method=\"get\" action=\"http:\/\/www.jianzhi8.com\/include\/gg_top.jsp\" target=\"_top\">");
document.writeln("<table border=\"0\" align=\"center\"  cellpadding=\"0\" bgcolor=\"#e7efff\" cellspacing=\"0\">");
document.writeln("<tr><td nowrap=\"nowrap\"  align=\"left\" height=\"25\">");
document.writeln("<input type=\"hidden\" name=\"domains\" value=\"jianzhi8.com\"><\/input>");
document.writeln("<label for=\"sbi\" style=\"display: none\">ÊäÈëÄúµÄËÑË÷×Ö´Ê<\/label>");
document.writeln("<input type=\"text\" name=\"q\" size=\"31\" maxlength=\"255\" value=\"\" id=\"sbi\"><\/input>");
document.writeln("<\/td>");
document.writeln("<td nowrap=\"nowrap\"  align=\"left\">");
document.writeln("<input type=\"radio\" name=\"sitesearch\" value=\"\" title=\'»¥ÁªÍøËÑË÷\' checked id=\"ss0\"><\/input>");
document.writeln("<label for=\"ss0\" title=\"ËÑË÷ÍøÂç\"><font size=\"-1\" color=\"#000000\">»¥ÁªÍø<\/font><\/label>");
document.writeln("<input type=\"radio\" name=\"sitesearch\" value=\"jianzhi8.com\" title=\'¼æÖ°ÍøÕ¾ÄÚËÑË÷\' id=\"ss1\"><\/input>");
document.writeln("<label for=\"ss1\" title=\"ËÑË÷ jianzhi8.com\"><font size=\"-1\" color=\"#000000\">±¾Õ¾ÄÚ<\/font><\/label>");
document.writeln("<label for=\"sbb\" style=\"display: none\">Ìá½»ËÑË÷±íµ¥<\/label>");
document.writeln("<input type=\"submit\" name=\"sa\" value=\"Google ËÑË÷\" id=\"sbb\"><\/input>");
document.writeln("<\/td>");
document.writeln("<td nowrap=\"nowrap\">");
document.writeln("<input type=\"hidden\" name=\"client\" value=\"pub-5637832140118238\"><\/input>");
document.writeln("<input type=\"hidden\" name=\"forid\" value=\"1\"><\/input>");
document.writeln("<input type=\"hidden\" name=\"channel\" value=\"1876792380\"><\/input>");
document.writeln("<input type=\"hidden\" name=\"ie\" value=\"GB2312\"><\/input>");
document.writeln("<input type=\"hidden\" name=\"oe\" value=\"GB2312\"><\/input>");
document.writeln("<input type=\"hidden\" name=\"flav\" value=\"0000\"><\/input>");
document.writeln("<input type=\"hidden\" name=\"sig\" value=\"uwi9k6wKx1e9LHkr\"><\/input>");
document.writeln("<input type=\"hidden\" name=\"cof\" value=\"GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:11\"><\/input>");
document.writeln("<input type=\"hidden\" name=\"hl\" value=\"zh-CN\"><\/input>");
document.writeln("<\/td><\/tr><\/table>");
document.writeln("<\/form>");
document.writeln("<!-- SiteSearch Google -->")
