document.writeln("<script type=\"text\/javascript\"><!--");
document.writeln("google_ad_client = \"pub-5637832140118238\";");
document.writeln("\/* 336x280, ´´½¨ÓÚ 10-12-13 *\/");
document.writeln("google_ad_slot = \"9266486549\";");
document.writeln("google_ad_width = 336;");
document.writeln("google_ad_height = 280;");
document.writeln("\/\/-->");
document.writeln("<\/script>");
document.writeln("<script type=\"text\/javascript\"");
document.writeln("src=\"http:\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js\">");
document.writeln("<\/script>");
