(function($){$.fn.ajaxSubmit=function(options){if(!this.length){log('ajaxSubmit: skipping submit process - no element selected');return this;}
if(typeof options=='function')
options={success:options};options=$.extend({url:this.attr('action')||window.location.toString(),type:this.attr('method')||'GET'},options||{});var veto={};this.trigger('form-pre-serialize',[this,options,veto]);if(veto.veto){log('ajaxSubmit: submit vetoed via form-pre-serialize trigger');return this;}
var a=this.formToArray(options.semantic);if(options.data){options.extraData=options.data;for(var n in options.data)
a.push({name:n,value:options.data[n]});}
if(options.beforeSubmit&&options.beforeSubmit(a,this,options)===false){log('ajaxSubmit: submit aborted via beforeSubmit callback');return this;}
this.trigger('form-submit-validate',[a,this,options,veto]);if(veto.veto){log('ajaxSubmit: submit vetoed via form-submit-validate trigger');return this;}
var q=$.param(a);if(options.type.toUpperCase()=='GET'){options.url+=(options.url.indexOf('?')>=0?'&':'?')+q;options.data=null;}
else
options.data=q;var $form=this,callbacks=[];if(options.resetForm)callbacks.push(function(){$form.resetForm();});if(options.clearForm)callbacks.push(function(){$form.clearForm();});if(!options.dataType&&options.target){var oldSuccess=options.success||function(){};callbacks.push(function(data){$(options.target).html(data).each(oldSuccess,arguments);});}
else if(options.success)
callbacks.push(options.success);options.success=function(data,status){for(var i=0,max=callbacks.length;i<max;i++)
callbacks[i](data,status,$form);};var files=$('input:file',this).fieldValue();var found=false;for(var j=0;j<files.length;j++)
if(files[j])
found=true;if(options.iframe||found){if($.browser.safari&&options.closeKeepAlive)
$.get(options.closeKeepAlive,fileUpload);else
fileUpload();}
else
$.ajax(options);this.trigger('form-submit-notify',[this,options]);return this;function fileUpload(){var form=$form[0];if($(':input[@name=submit]',form).length){alert('Error: Form elements must not be named "submit".');return;}
var opts=$.extend({},$.ajaxSettings,options);var id='jqFormIO'+(new Date().getTime());var $io=$('<iframe id="'+id+'" name="'+id+'" />');var io=$io[0];if($.browser.msie||$.browser.opera)
io.src='javascript:false;document.write("");';$io.css({position:'absolute',top:'-1000px',left:'-1000px'});var xhr={responseText:null,responseXML:null,status:0,statusText:'n/a',getAllResponseHeaders:function(){},getResponseHeader:function(){},setRequestHeader:function(){}};var g=opts.global;if(g&&!$.active++)$.event.trigger("ajaxStart");if(g)$.event.trigger("ajaxSend",[xhr,opts]);var cbInvoked=0;var timedOut=0;var sub=form.clk;if(sub){var n=sub.name;if(n&&!sub.disabled){options.extraData=options.extraData||{};options.extraData[n]=sub.value;if(sub.type=="image"){options.extraData[name+'.x']=form.clk_x;options.extraData[name+'.y']=form.clk_y;}}}
setTimeout(function(){var t=$form.attr('target'),a=$form.attr('action');$form.attr({target:id,encoding:'multipart/form-data',enctype:'multipart/form-data',method:'POST',action:opts.url});if(opts.timeout)
setTimeout(function(){timedOut=true;cb();},opts.timeout);var extraInputs=[];try{if(options.extraData)
for(var n in options.extraData)
extraInputs.push($('<input type="hidden" name="'+n+'" value="'+options.extraData[n]+'" />').appendTo(form)[0]);$io.appendTo('body');io.attachEvent?io.attachEvent('onload',cb):io.addEventListener('load',cb,false);form.submit();}
finally{$form.attr('action',a);t?$form.attr('target',t):$form.removeAttr('target');$(extraInputs).remove();}},10);function cb(){if(cbInvoked++)return;io.detachEvent?io.detachEvent('onload',cb):io.removeEventListener('load',cb,false);var operaHack=0;var ok=true;try{if(timedOut)throw'timeout';var data,doc;doc=io.contentWindow?io.contentWindow.document:io.contentDocument?io.contentDocument:io.document;if(doc.body==null&&!operaHack&&$.browser.opera){operaHack=1;cbInvoked--;setTimeout(cb,100);return;}
xhr.responseText=doc.body?doc.body.innerHTML:null;xhr.responseXML=doc.XMLDocument?doc.XMLDocument:doc;xhr.getResponseHeader=function(header){var headers={'content-type':opts.dataType};return headers[header];};if(opts.dataType=='json'||opts.dataType=='script'){var ta=doc.getElementsByTagName('textarea')[0];xhr.responseText=ta?ta.value:xhr.responseText;}
else if(opts.dataType=='xml'&&!xhr.responseXML&&xhr.responseText!=null){xhr.responseXML=toXml(xhr.responseText);}
data=$.httpData(xhr,opts.dataType);}
catch(e){ok=false;$.handleError(opts,xhr,'error',e);}
if(ok){opts.success(data,'success');if(g)$.event.trigger("ajaxSuccess",[xhr,opts]);}
if(g)$.event.trigger("ajaxComplete",[xhr,opts]);if(g&&!--$.active)$.event.trigger("ajaxStop");if(opts.complete)opts.complete(xhr,ok?'success':'error');setTimeout(function(){$io.remove();xhr.responseXML=null;},100);};function toXml(s,doc){if(window.ActiveXObject){doc=new ActiveXObject('Microsoft.XMLDOM');doc.async='false';doc.loadXML(s);}
else
doc=(new DOMParser()).parseFromString(s,'text/xml');return(doc&&doc.documentElement&&doc.documentElement.tagName!='parsererror')?doc:null;};};};$.fn.ajaxForm=function(options){return this.ajaxFormUnbind().bind('submit.form-plugin',function(){$(this).ajaxSubmit(options);return false;}).each(function(){$(":submit,input:image",this).bind('click.form-plugin',function(e){var $form=this.form;$form.clk=this;if(this.type=='image'){if(e.offsetX!=undefined){$form.clk_x=e.offsetX;$form.clk_y=e.offsetY;}else if(typeof $.fn.offset=='function'){var offset=$(this).offset();$form.clk_x=e.pageX-offset.left;$form.clk_y=e.pageY-offset.top;}else{$form.clk_x=e.pageX-this.offsetLeft;$form.clk_y=e.pageY-this.offsetTop;}}
setTimeout(function(){$form.clk=$form.clk_x=$form.clk_y=null;},10);});});};$.fn.ajaxFormUnbind=function(){this.unbind('submit.form-plugin');return this.each(function(){$(":submit,input:image",this).unbind('click.form-plugin');});};$.fn.formToArray=function(semantic){var a=[];if(this.length==0)return a;var form=this[0];var els=semantic?form.getElementsByTagName('*'):form.elements;if(!els)return a;for(var i=0,max=els.length;i<max;i++){var el=els[i];var n=el.name;if(!n)continue;if(semantic&&form.clk&&el.type=="image"){if(!el.disabled&&form.clk==el)
a.push({name:n+'.x',value:form.clk_x},{name:n+'.y',value:form.clk_y});continue;}
var v=$.fieldValue(el,true);if(v&&v.constructor==Array){for(var j=0,jmax=v.length;j<jmax;j++)
a.push({name:n,value:v[j]});}
else if(v!==null&&typeof v!='undefined')
a.push({name:n,value:v});}
if(!semantic&&form.clk){var inputs=form.getElementsByTagName("input");for(var i=0,max=inputs.length;i<max;i++){var input=inputs[i];var n=input.name;if(n&&!input.disabled&&input.type=="image"&&form.clk==input)
a.push({name:n+'.x',value:form.clk_x},{name:n+'.y',value:form.clk_y});}}
return a;};$.fn.formSerialize=function(semantic){return $.param(this.formToArray(semantic));};$.fn.fieldSerialize=function(successful){var a=[];this.each(function(){var n=this.name;if(!n)return;var v=$.fieldValue(this,successful);if(v&&v.constructor==Array){for(var i=0,max=v.length;i<max;i++)
a.push({name:n,value:v[i]});}
else if(v!==null&&typeof v!='undefined')
a.push({name:this.name,value:v});});return $.param(a);};$.fn.fieldValue=function(successful){for(var val=[],i=0,max=this.length;i<max;i++){var el=this[i];var v=$.fieldValue(el,successful);if(v===null||typeof v=='undefined'||(v.constructor==Array&&!v.length))
continue;v.constructor==Array?$.merge(val,v):val.push(v);}
return val;};$.fieldValue=function(el,successful){var n=el.name,t=el.type,tag=el.tagName.toLowerCase();if(typeof successful=='undefined')successful=true;if(successful&&(!n||el.disabled||t=='reset'||t=='button'||(t=='checkbox'||t=='radio')&&!el.checked||(t=='submit'||t=='image')&&el.form&&el.form.clk!=el||tag=='select'&&el.selectedIndex==-1))
return null;if(tag=='select'){var index=el.selectedIndex;if(index<0)return null;var a=[],ops=el.options;var one=(t=='select-one');var max=(one?index+1:ops.length);for(var i=(one?index:0);i<max;i++){var op=ops[i];if(op.selected){var v=$.browser.msie&&!(op.attributes['value'].specified)?op.text:op.value;if(one)return v;a.push(v);}}
return a;}
return el.value;};$.fn.clearForm=function(){return this.each(function(){$('input,select,textarea',this).clearFields();});};$.fn.clearFields=$.fn.clearInputs=function(){return this.each(function(){var t=this.type,tag=this.tagName.toLowerCase();if(t=='text'||t=='password'||tag=='textarea')
this.value='';else if(t=='checkbox'||t=='radio')
this.checked=false;else if(tag=='select')
this.selectedIndex=-1;});};$.fn.resetForm=function(){return this.each(function(){if(typeof this.reset=='function'||(typeof this.reset=='object'&&!this.reset.nodeType))
this.reset();});};$.fn.enable=function(b){if(b==undefined)b=true;return this.each(function(){this.disabled=!b});};$.fn.select=function(select){if(select==undefined)select=true;return this.each(function(){var t=this.type;if(t=='checkbox'||t=='radio')
this.checked=select;else if(this.tagName.toLowerCase()=='option'){var $sel=$(this).parent('select');if(select&&$sel[0]&&$sel[0].type=='select-one'){$sel.find('option').select(false);}
this.selected=select;}});};function log(){if($.fn.ajaxSubmit.debug&&window.console&&window.console.log)
window.console.log('[jquery.form] '+Array.prototype.join.call(arguments,''));};})(jQuery);
if(jQuery)(function($){$.extend($.fn,{fileTree:function(o,h){if(!o)var o={};if(o.root==undefined)o.root='/';if(o.script==undefined)o.script='jqueryFileTree.php';if(o.folderEvent==undefined)o.folderEvent='click';if(o.expandSpeed==undefined)o.expandSpeed=500;if(o.collapseSpeed==undefined)o.collapseSpeed=500;if(o.expandEasing==undefined)o.expandEasing=null;if(o.collapseEasing==undefined)o.collapseEasing=null;if(o.multiFolder==undefined)o.multiFolder=true;if(o.loadMessage==undefined)o.loadMessage='Loading...';$(this).each(function(){function showTree(c,t){$(c).addClass('wait');$(".jqueryFileTree.start").remove();$.post(o.script,{dir:t},function(data){$(c).find('.start').html('');$(c).removeClass('wait').append(data);if(o.root==t)$(c).find('UL:hidden').show();else $(c).find('UL:hidden').slideDown({duration:o.expandSpeed,easing:o.expandEasing});bindTree(c);});}
function bindTree(t){$(t).find('LI A').bind(o.folderEvent,function(){if($(this).parent().hasClass('directory')){if($(this).parent().hasClass('collapsed')){if(!o.multiFolder){$(this).parent().parent().find('UL').slideUp({duration:o.collapseSpeed,easing:o.collapseEasing});$(this).parent().parent().find('LI.directory').removeClass('expanded').addClass('collapsed');}
$(this).parent().find('UL').remove();showTree($(this).parent(),escape($(this).attr('rel').match(/.*\//)));$(this).parent().removeClass('collapsed').addClass('expanded');}else{$(this).parent().find('UL').slideUp({duration:o.collapseSpeed,easing:o.collapseEasing});$(this).parent().removeClass('expanded').addClass('collapsed');}}else{h($(this).attr('rel'));}
return false;});if(o.folderEvent.toLowerCase!='click')$(t).find('LI A').bind('click',function(){return false;});}
$(this).html('<ul class="jqueryFileTree start"><li class="wait">'+o.loadMessage+'<li></ul>');showTree($(this),escape(o.root));});}});})(jQuery);
var tb_pathToImage="images/loadingAnimation.gif";$(document).ready(function(){tb_init('a.thickbox, area.thickbox, input.thickbox');imgLoader=new Image();imgLoader.src=tb_pathToImage;});function tb_init(domChunk){$(domChunk).click(function(){var t=this.title||this.name||null;var a=this.href||this.alt;var g=this.rel||false;tb_show(t,a,g);this.blur();return false;});}
function tb_show(caption,url,imageGroup){try{if(typeof document.body.style.maxHeight==="undefined"){$("body","html").css({height:"100%",width:"100%"});$("html").css("overflow","hidden");if(document.getElementById("TB_HideSelect")===null){$("body").append("<iframe id='TB_HideSelect'></iframe><div id='TB_overlay'></div><div id='TB_window'></div>");$("#TB_overlay").click(tb_remove);}}else{if(document.getElementById("TB_overlay")===null){$("body").append("<div id='TB_overlay'></div><div id='TB_window'></div>");$("#TB_overlay").click(tb_remove);}}
if(tb_detectMacXFF()){$("#TB_overlay").addClass("TB_overlayMacFFBGHack");}else{$("#TB_overlay").addClass("TB_overlayBG");}
if(caption===null){caption="";}
$("body").append("<div id='TB_load'><img src='"+imgLoader.src+"' /></div>");$('#TB_load').show();var baseURL;if(url.indexOf("?")!==-1){baseURL=url.substr(0,url.indexOf("?"));}else{baseURL=url;}
var urlString=/\.jpg$|\.jpeg$|\.png$|\.gif$|\.bmp$/;var urlType=baseURL.toLowerCase().match(urlString);if(urlType=='.jpg'||urlType=='.jpeg'||urlType=='.png'||urlType=='.gif'||urlType=='.bmp'){TB_PrevCaption="";TB_PrevURL="";TB_PrevHTML="";TB_NextCaption="";TB_NextURL="";TB_NextHTML="";TB_imageCount="";TB_FoundURL=false;if(imageGroup){TB_TempArray=$("a[@rel="+imageGroup+"]").get();for(TB_Counter=0;((TB_Counter<TB_TempArray.length)&&(TB_NextHTML===""));TB_Counter++){var urlTypeTemp=TB_TempArray[TB_Counter].href.toLowerCase().match(urlString);if(!(TB_TempArray[TB_Counter].href==url)){if(TB_FoundURL){TB_NextCaption=TB_TempArray[TB_Counter].title;TB_NextURL=TB_TempArray[TB_Counter].href;TB_NextHTML="<span id='TB_next'>&nbsp;&nbsp;<a href='#'>Next &gt;</a></span>";}else{TB_PrevCaption=TB_TempArray[TB_Counter].title;TB_PrevURL=TB_TempArray[TB_Counter].href;TB_PrevHTML="<span id='TB_prev'>&nbsp;&nbsp;<a href='#'>&lt; Prev</a></span>";}}else{TB_FoundURL=true;TB_imageCount="Image "+(TB_Counter+1)+" of "+(TB_TempArray.length);}}}
imgPreloader=new Image();imgPreloader.onload=function(){imgPreloader.onload=null;var pagesize=tb_getPageSize();var x=pagesize[0]-150;var y=pagesize[1]-150;var imageWidth=imgPreloader.width;var imageHeight=imgPreloader.height;if(imageWidth>x){imageHeight=imageHeight*(x/imageWidth);imageWidth=x;if(imageHeight>y){imageWidth=imageWidth*(y/imageHeight);imageHeight=y;}}else if(imageHeight>y){imageWidth=imageWidth*(y/imageHeight);imageHeight=y;if(imageWidth>x){imageHeight=imageHeight*(x/imageWidth);imageWidth=x;}}
TB_WIDTH=imageWidth+30;TB_HEIGHT=imageHeight+60;$("#TB_window").append("<a href='' id='TB_ImageOff' title='Close'><img id='TB_Image' src='"+url+"' width='"+imageWidth+"' height='"+imageHeight+"' alt='"+caption+"'/></a>"+"<div id='TB_caption'>"+caption+"<div id='TB_secondLine'>"+TB_imageCount+TB_PrevHTML+TB_NextHTML+"</div></div><div id='TB_closeWindow'><a href='#' id='TB_closeWindowButton' title='Close'>close</a> or Esc Key</div>");$("#TB_closeWindowButton").click(tb_remove);if(!(TB_PrevHTML==="")){function goPrev(){if($(document).unbind("click",goPrev)){$(document).unbind("click",goPrev);}
$("#TB_window").remove();$("body").append("<div id='TB_window'></div>");tb_show(TB_PrevCaption,TB_PrevURL,imageGroup);return false;}
$("#TB_prev").click(goPrev);}
if(!(TB_NextHTML==="")){function goNext(){$("#TB_window").remove();$("body").append("<div id='TB_window'></div>");tb_show(TB_NextCaption,TB_NextURL,imageGroup);return false;}
$("#TB_next").click(goNext);}
document.onkeydown=function(e){if(e==null){keycode=event.keyCode;}else{keycode=e.which;}
if(keycode==27){tb_remove();}else if(keycode==190){if(!(TB_NextHTML=="")){document.onkeydown="";goNext();}}else if(keycode==188){if(!(TB_PrevHTML=="")){document.onkeydown="";goPrev();}}};tb_position();$("#TB_load").remove();$("#TB_ImageOff").click(tb_remove);$("#TB_window").css({display:"block"});};imgPreloader.src=url;}else{var queryString=url.replace(/^[^\?]+\??/,'');var params=tb_parseQuery(queryString);TB_WIDTH=(params['width']*1)+30||630;TB_HEIGHT=(params['height']*1)+40||440;ajaxContentW=TB_WIDTH-30;ajaxContentH=TB_HEIGHT-45;if(url.indexOf('TB_iframe')!=-1){urlNoQuery=url.split('TB_');$("#TB_iframeContent").remove();if(params['modal']!="true"){$("#TB_window").append("<div id='TB_title'><div id='TB_ajaxWindowTitle'>"+caption+"</div><div id='TB_closeAjaxWindow'><a href='#' id='TB_closeWindowButton' title='Close'>close</a> or Esc Key</div></div><iframe frameborder='0' hspace='0' src='"+urlNoQuery[0]+"' id='TB_iframeContent' name='TB_iframeContent"+Math.round(Math.random()*1000)+"' onload='tb_showIframe()' style='width:"+(ajaxContentW+29)+"px;height:"+(ajaxContentH+17)+"px;' > </iframe>");}else{$("#TB_overlay").unbind();$("#TB_window").append("<iframe frameborder='0' hspace='0' src='"+urlNoQuery[0]+"' id='TB_iframeContent' name='TB_iframeContent"+Math.round(Math.random()*1000)+"' onload='tb_showIframe()' style='width:"+(ajaxContentW+29)+"px;height:"+(ajaxContentH+17)+"px;'> </iframe>");}}else{if($("#TB_window").css("display")!="block"){if(params['modal']!="true"){$("#TB_window").append("<div id='TB_title'><div id='TB_ajaxWindowTitle'>"+caption+"</div><div id='TB_closeAjaxWindow'><a href='#' id='TB_closeWindowButton'>close</a> or Esc Key</div></div><div id='TB_ajaxContent' style='width:"+ajaxContentW+"px;height:"+ajaxContentH+"px'></div>");}else{$("#TB_overlay").unbind();$("#TB_window").append("<div id='TB_ajaxContent' class='TB_modal' style='width:"+ajaxContentW+"px;height:"+ajaxContentH+"px;'></div>");}}else{$("#TB_ajaxContent")[0].style.width=ajaxContentW+"px";$("#TB_ajaxContent")[0].style.height=ajaxContentH+"px";$("#TB_ajaxContent")[0].scrollTop=0;$("#TB_ajaxWindowTitle").html(caption);}}
$("#TB_closeWindowButton").click(tb_remove);if(url.indexOf('TB_inline')!=-1){$("#TB_ajaxContent").append($('#'+params['inlineId']).children());$("#TB_window").unload(function(){$('#'+params['inlineId']).append($("#TB_ajaxContent").children());});tb_position();$("#TB_load").remove();$("#TB_window").css({display:"block"});}else if(url.indexOf('TB_iframe')!=-1){tb_position();if($.browser.safari){$("#TB_load").remove();$("#TB_window").css({display:"block"});}}else{$("#TB_ajaxContent").load(url+="&random="+(new Date().getTime()),function(){tb_position();$("#TB_load").remove();tb_init("#TB_ajaxContent a.thickbox");$("#TB_window").css({display:"block"});});}}
if(!params['modal']){document.onkeyup=function(e){if(e==null){keycode=event.keyCode;}else{keycode=e.which;}
if(keycode==27){tb_remove();}};}}catch(e){}}
function tb_showIframe(){$("#TB_load").remove();$("#TB_window").css({display:"block"});}
function tb_remove(){$("#TB_imageOff").unbind("click");$("#TB_closeWindowButton").unbind("click");$("#TB_window").fadeOut("fast",function(){$('#TB_window,#TB_overlay,#TB_HideSelect').trigger("unload").unbind().remove();});$("#TB_load").remove();if(typeof document.body.style.maxHeight=="undefined"){$("body","html").css({height:"auto",width:"auto"});$("html").css("overflow","");}
document.onkeydown="";document.onkeyup="";return false;}
function tb_position(){$("#TB_window").css({marginLeft:'-'+parseInt((TB_WIDTH/2),10)+'px',width:TB_WIDTH+'px'});if(!(jQuery.browser.msie&&jQuery.browser.version<7)){$("#TB_window").css({marginTop:'-'+parseInt((TB_HEIGHT/2),10)+'px'});}}
function tb_parseQuery(query){var Params={};if(!query){return Params;}
var Pairs=query.split(/[;&]/);for(var i=0;i<Pairs.length;i++){var KeyVal=Pairs[i].split('=');if(!KeyVal||KeyVal.length!=2){continue;}
var key=unescape(KeyVal[0]);var val=unescape(KeyVal[1]);val=val.replace(/\+/g,' ');Params[key]=val;}
return Params;}
function tb_getPageSize(){var de=document.documentElement;var w=window.innerWidth||self.innerWidth||(de&&de.clientWidth)||document.body.clientWidth;var h=window.innerHeight||self.innerHeight||(de&&de.clientHeight)||document.body.clientHeight;arrayPageSize=[w,h];return arrayPageSize;}
function tb_detectMacXFF(){var userAgent=navigator.userAgent.toLowerCase();if(userAgent.indexOf('mac')!=-1&&userAgent.indexOf('firefox')!=-1){return true;}}
jQuery.preloadImages=function()
{var imgs=new Array();for(var i=0;i<arguments.length;i++)
{imgs[i]=jQuery("<img>").attr("src",arguments[i]);}
return imgs;}
jQuery.NiceJForms={options:{selectRightSideWidth:21,selectLeftSideWidth:8,selectAreaHeight:21,selectAreaOptionsOverlap:2,imagesPath:"images/"},selectText:'please select',preloads:new Array(),inputs:new Array(),labels:new Array(),textareas:new Array(),selects:new Array(),radios:new Array(),checkboxes:new Array(),texts:new Array(),buttons:new Array(),radioLabels:new Array(),checkboxLabels:new Array(),hasImages:true,keyPressed:function(event)
{var pressedKey=event.charCode||event.keyCode||-1;switch(pressedKey)
{case 40:var fieldId=this.parentNode.parentNode.id.replace(/sarea/g,"");var linkNo=0;for(var q=0;q<selects[fieldId].options.length;q++){if(selects[fieldId].options[q].selected){linkNo=q;}}
++linkNo;if(linkNo>=selects[fieldId].options.length){linkNo=0;}
selectMe(selects[fieldId].id,linkNo,fieldId);break;case 38:var fieldId=this.parentNode.parentNode.id.replace(/sarea/g,"");var linkNo=0;for(var q=0;q<selects[fieldId].options.length;q++){if(selects[fieldId].options[q].selected){linkNo=q;}}
--linkNo;if(linkNo<0){linkNo=selects[fieldId].options.length-1;}
selectMe(selects[fieldId].id,linkNo,fieldId);break;default:break;}},build:function(options)
{if(options)
jQuery.extend(jQuery.NiceJForms.options,options);if(window.event){jQuery('body',document).bind('keyup',jQuery.NiceJForms.keyPressed);}else{jQuery(document).bind('keyup',jQuery.NiceJForms.keyPressed);}
var testImg=document.createElement('img');$(testImg).attr("src",jQuery.NiceJForms.options.imagesPath+"blank.gif");jQuery('body').append(testImg);if(testImg.complete)
{if(testImg.offsetWidth=='1'){jQuery.NiceJForms.hasImages=true;}
else{jQuery.NiceJForms.hasImages=false;}}
$(testImg).remove();if(jQuery.NiceJForms.hasImages)
{$('form.niceform').each(function()
{el=jQuery(this);jQuery.NiceJForms.preloadImages();jQuery.NiceJForms.getElements(el);jQuery.NiceJForms.replaceRadios();jQuery.NiceJForms.replaceCheckboxes();jQuery.NiceJForms.replaceSelects();if(!$.browser.safari){jQuery.NiceJForms.replaceTexts();jQuery.NiceJForms.replaceTextareas();jQuery.NiceJForms.buttonHovers();}});}},preloadImages:function()
{jQuery.NiceJForms.preloads=$.preloadImages(jQuery.NiceJForms.options.imagesPath+"button_left_xon.gif",jQuery.NiceJForms.options.imagesPath+"button_right_xon.gif",jQuery.NiceJForms.options.imagesPath+"input_left_xon.gif",jQuery.NiceJForms.options.imagesPath+"input_right_xon.gif",jQuery.NiceJForms.options.imagesPath+"txtarea_bl_xon.gif",jQuery.NiceJForms.options.imagesPath+"txtarea_br_xon.gif",jQuery.NiceJForms.options.imagesPath+"txtarea_cntr_xon.gif",jQuery.NiceJForms.options.imagesPath+"txtarea_l_xon.gif",jQuery.NiceJForms.options.imagesPath+"txtarea_tl_xon.gif",jQuery.NiceJForms.options.imagesPath+"txtarea_tr_xon.gif");},getElements:function(elm)
{el=elm?jQuery(elm):jQuery(this);var r=0;var c=0;var t=0;var rl=0;var cl=0;var tl=0;var b=0;jQuery.NiceJForms.inputs=$('input',el);jQuery.NiceJForms.labels=$('label',el);jQuery.NiceJForms.textareas=$('textarea',el);jQuery.NiceJForms.selects=$('select',el);jQuery.NiceJForms.radios=$('input[@type=radio]',el);jQuery.NiceJForms.checkboxes=$('input[@type=checkbox]',el);jQuery.NiceJForms.texts=$('input[@type=text]',el).add($('input[@type=password]',el));jQuery.NiceJForms.buttons=$('input[@type=submit]',el).add($('input[@type=button]',el));jQuery.NiceJForms.labels.each(function(i){labelFor=$(jQuery.NiceJForms.labels[i]).attr("for");jQuery.NiceJForms.radios.each(function(q){if(labelFor==$(jQuery.NiceJForms.radios[q]).attr("id"))
{if(jQuery.NiceJForms.radios[q].checked)
{$(jQuery.NiceJForms.labels[i]).removeClass().addClass("chosen");}
jQuery.NiceJForms.radioLabels[rl]=jQuery.NiceJForms.labels[i];++rl;}})
jQuery.NiceJForms.checkboxes.each(function(x){if(labelFor==$(this).attr("id"))
{if(this.checked)
{$(jQuery.NiceJForms.labels[i]).removeClass().addClass("chosen");}
jQuery.NiceJForms.checkboxLabels[cl]=jQuery.NiceJForms.labels[i];++cl;}})});},replaceRadios:function()
{var self=this;jQuery.NiceJForms.radios.each(function(q){$(this).removeClass().addClass('outtaHere');var radioArea=document.createElement('div');if(this.checked){$(radioArea).removeClass().addClass("radioAreaChecked");}else{$(radioArea).removeClass().addClass("radioArea");};radioPos=jQuery.iUtil.getPosition(this);jQuery(radioArea).attr({id:'myRadio'+q}).css({left:radioPos.x+'px',top:radioPos.y+'px',margin:'1px'}).bind('click',{who:q},function(e){self.rechangeRadios(e)}).insertBefore($(this));$(jQuery.NiceJForms.radioLabels[q]).bind('click',{who:q},function(e){self.rechangeRadios(e)});if(!$.browser.msie){$(this).bind('focus',function(){self.focusRadios(q)}).bind('blur',function(){self.blurRadios(q)});}
$(this).bind('click',function(e){self.radioEvent(e)});});return true;},changeRadios:function(who){var self=this;if(jQuery.NiceJForms.radios[who].checked){jQuery.NiceJForms.radios.each(function(q){if($(this).attr("name")==$(jQuery.NiceJForms.radios[who]).attr("name"))
{this.checked=false;$(jQuery.NiceJForms.radioLabels[q]).removeClass();}});jQuery.NiceJForms.radios[who].checked=true;$(jQuery.NiceJForms.radioLabels[who]).addClass("chosen");self.checkRadios(who);}},rechangeRadios:function(e)
{who=e.data.who;if(!jQuery.NiceJForms.radios[who].checked){for(var q=0;q<jQuery.NiceJForms.radios.length;q++)
{if(jQuery.NiceJForms.radios[q].name==jQuery.NiceJForms.radios[who].name)
{jQuery.NiceJForms.radios[q].checked=false;jQuery.NiceJForms.radioLabels[q].className="";}}
$(jQuery.NiceJForms.radios[who]).attr('checked',true);jQuery.NiceJForms.radioLabels[who].className="chosen";jQuery.NiceJForms.checkRadios(who);}},checkRadios:function(who){$('div').each(function(q){if($(this).is(".radioAreaChecked")&&$(this).next().attr("name")==$(jQuery.NiceJForms.radios[who]).attr("name")){$(this).removeClass().addClass("radioArea");}});$('#myRadio'+who).toggleClass("radioAreaChecked");},focusRadios:function(who){$('#myRadio'+who).css({border:'1px dotted #333',margin:'0'});return false;},blurRadios:function(who){$('#myRadio'+who).css({border:'none',margin:'1px'});return false;},radioEvent:function(e){var self=this;if(!e)var e=window.event;if(e.type=="click"){for(var q=0;q<jQuery.NiceJForms.radios.length;q++){if(this==jQuery.NiceJForms.radios[q]){self.changeRadios(q);break;}}}},replaceCheckboxes:function()
{var self=this;jQuery.NiceJForms.checkboxes.each(function(q){$(jQuery.NiceJForms.checkboxes[q]).removeClass().addClass('outtaHere');var checkboxArea=document.createElement('div');if(jQuery.NiceJForms.checkboxes[q].checked){$(checkboxArea).removeClass().addClass("checkboxAreaChecked");}else{$(checkboxArea).removeClass().addClass("checkboxArea");};checkboxPos=jQuery.iUtil.getPosition(jQuery.NiceJForms.checkboxes[q]);jQuery(checkboxArea).attr({id:'myCheckbox'+q}).css({left:checkboxPos.x+'px',top:checkboxPos.y+'px',margin:'1px'}).bind('click',{who:q},function(e){self.rechangeCheckboxes(e)}).insertBefore($(jQuery.NiceJForms.checkboxes[q]));if(!$.browser.safari)
{$(jQuery.NiceJForms.checkboxLabels[q]).bind('click',{who:q},function(e){self.changeCheckboxes(e)})}
else{$(jQuery.NiceJForms.checkboxLabels[q]).bind('click',{who:q},function(e){self.rechangeCheckboxes(e)})}
if(!$.browser.msie)
{$(jQuery.NiceJForms.checkboxes[q]).bind('focus',{who:q},function(e){self.focusCheckboxes(e)});$(jQuery.NiceJForms.checkboxes[q]).bind('blur',{who:q},function(e){self.blurCheckboxes(e)});}});return true;},rechangeCheckboxes:function(e)
{who=e.data.who;var tester=false;if($(jQuery.NiceJForms.checkboxLabels[who]).is(".chosen")){tester=false;$(jQuery.NiceJForms.checkboxLabels[who]).removeClass();}
else if(jQuery.NiceJForms.checkboxLabels[who].className==""){tester=true;$(jQuery.NiceJForms.checkboxLabels[who]).addClass("chosen");}
jQuery.NiceJForms.checkboxes[who].checked=tester;jQuery.NiceJForms.checkCheckboxes(who,tester);},checkCheckboxes:function(who,action)
{var what=$('#myCheckbox'+who);if(action==true){$(what).removeClass().addClass("checkboxAreaChecked");}
if(action==false){$(what).removeClass().addClass("checkboxArea");}},focusCheckboxes:function(who)
{var what=$('#myCheckbox'+who);$(what).css({border:"1px dotted #333",margin:"0"});return false;},changeCheckboxes:function(e){who=e.data.who;if($(jQuery.NiceJForms.checkboxLabels[who]).is(".chosen")){jQuery.NiceJForms.checkboxes[who].checked=true;$(jQuery.NiceJForms.checkboxLabels[who]).removeClass();jQuery.NiceJForms.checkCheckboxes(who,false);}
else if(jQuery.NiceJForms.checkboxLabels[who].className==""){jQuery.NiceJForms.checkboxes[who].checked=false;$(jQuery.NiceJForms.checkboxLabels[who]).toggleClass("chosen");jQuery.NiceJForms.checkCheckboxes(who,true);}},blurCheckboxes:function(who)
{var what=$('#myCheckbox'+who);$(what).css({border:'none',margin:'1px'});return false;},replaceSelects:function()
{var self=this;jQuery.NiceJForms.selects.each(function(q){var selectArea=document.createElement('div');var left=document.createElement('div');var right=document.createElement('div');var center=document.createElement('div');var button=document.createElement('a');var text=document.createTextNode(jQuery.NiceJForms.selectText);var selectWidth=parseInt(this.className.replace(/width_/g,""));jQuery(center).attr({id:'mySelectText'+q}).css({width:selectWidth-10+'px'});jQuery(selectArea).attr({id:'sarea'+q}).css({width:selectWidth+jQuery.NiceJForms.options.selectRightSideWidth+jQuery.NiceJForms.options.selectLeftSideWidth+'px'}).addClass("selectArea");jQuery(button).css({width:selectWidth+jQuery.NiceJForms.options.selectRightSideWidth+jQuery.NiceJForms.options.selectLeftSideWidth+'px',marginLeft:-selectWidth-jQuery.NiceJForms.options.selectLeftSideWidth+'px',cursor:'pointer'}).addClass("selectButton").bind('click',{who:q},function(e){self.showOptions(e)}).keydown(jQuery.NiceJForms.keyPressed);jQuery(left).addClass("left");jQuery(right).addClass("right").append(button);jQuery(center).addClass("center").append(text);jQuery(selectArea).append(left).append(right).append(center).insertBefore(this);$(this).hide();var optionsDiv=document.createElement('div');selectAreaPos=jQuery.iUtil.getPosition(selectArea);jQuery(optionsDiv).attr({id:"optionsDiv"+q}).css({width:selectWidth+1+'px',left:selectAreaPos.x+'px',top:selectAreaPos.y+jQuery.NiceJForms.options.selectAreaHeight-jQuery.NiceJForms.options.selectAreaOptionsOverlap+'px'}).addClass("optionsDivInvisible");$(jQuery.NiceJForms.selects[q]).children().each(function(w){var optionHolder=document.createElement('p');var optionLink=document.createElement('a');var optionTxt=document.createTextNode(jQuery.NiceJForms.selects[q].options[w].text);jQuery(optionLink).attr({href:'#'}).css({cursor:'pointer'}).append(optionTxt).bind('click',{who:q,id:jQuery.NiceJForms.selects[q].id,option:w,select:q},function(e){self.showOptions(e);self.selectMe(jQuery.NiceJForms.selects[q].id,w,q)});jQuery(optionHolder).append(optionLink);jQuery(optionsDiv).append(optionHolder);if(jQuery.NiceJForms.selects[q].options[w].selected){self.selectMe($(jQuery.NiceJForms.selects[q]).attr("id"),w,q);}});jQuery('body').append(optionsDiv);});},selectMe:function(selectFieldId,linkNo,selectNo){selectField=$('#'+selectFieldId);sFoptions=selectField.children();selectField.children().each(function(k){if(k==linkNo){sFoptions[k].selected="selected";}
else{sFoptions[k].selected="";}});textVar=$("#mySelectText"+selectNo);var newText=document.createTextNode($(sFoptions[linkNo]).text());textVar.empty().append(newText);},showOptions:function(e){var self=this;$("#optionsDiv"+e.data.who).toggleClass("optionsDivVisible").toggleClass("optionsDivInvisible").mouseout(function(e){self.hideOptions(e)});},hideOptions:function(e){if(!e)var e=window.event;var reltg=(e.relatedTarget)?e.relatedTarget:e.toElement;if(((reltg.nodeName!='A')&&(reltg.nodeName!='DIV'))||((reltg.nodeName=='A')&&(reltg.className=="selectButton")&&(reltg.nodeName!='DIV'))){this.className="optionsDivInvisible";};e.cancelBubble=true;if(e.stopPropagation)e.stopPropagation();},replaceTexts:function(){jQuery.NiceJForms.texts.each(function(q){$(jQuery.NiceJForms.texts[q]).css({width:this.size*10+'px'});var txtLeft=new Image();jQuery(txtLeft).attr({src:jQuery.NiceJForms.options.imagesPath+"input_left.gif"}).addClass("inputCorner");var txtRight=new Image();jQuery(txtRight).attr({src:jQuery.NiceJForms.options.imagesPath+"input_right.gif"}).addClass("inputCorner");$(jQuery.NiceJForms.texts[q]).before(txtLeft).after(txtRight).addClass("textinput");$(jQuery.NiceJForms.texts[q]).focus(function(){$(this).addClass("textinputHovered");$(this).prev().attr('src',jQuery.NiceJForms.options.imagesPath+"input_left_xon.gif");$(this).next().attr('src',jQuery.NiceJForms.options.imagesPath+"input_right_xon.gif");});$(jQuery.NiceJForms.texts[q]).blur(function(){$(this).removeClass().addClass("textinput");$(this).prev().attr('src',jQuery.NiceJForms.options.imagesPath+"input_left.gif");$(this).next().attr('src',jQuery.NiceJForms.options.imagesPath+"input_right.gif");});});},replaceTextareas:function(){jQuery.NiceJForms.textareas.each(function(q){var where=$(this).parent();var where2=$(this).prev();$(this).css({width:$(this).attr("cols")*10+'px',height:$(this).attr("rows")*10+'px'});var container=document.createElement('div');jQuery(container).css({width:jQuery.NiceJForms.textareas[q].cols*10+20+'px',height:jQuery.NiceJForms.textareas[q].rows*10+20+'px'}).addClass("txtarea");var topRight=document.createElement('div');jQuery(topRight).addClass("tr");var topLeft=new Image();jQuery(topLeft).attr({src:jQuery.NiceJForms.options.imagesPath+'txtarea_tl.gif'}).addClass("txt_corner");var centerRight=document.createElement('div');jQuery(centerRight).addClass("cntr");var centerLeft=document.createElement('div');jQuery(centerLeft).addClass("cntr_l");if(!$.browser.msie){jQuery(centerLeft).height(jQuery.NiceJForms.textareas[q].rows*10+10+'px')}
else{jQuery(centerLeft).height(jQuery.NiceJForms.textareas[q].rows*10+12+'px')};var bottomRight=document.createElement('div');jQuery(bottomRight).addClass("br");var bottomLeft=new Image();jQuery(bottomLeft).attr({src:jQuery.NiceJForms.options.imagesPath+'txtarea_bl.gif'}).addClass('txt_corner');jQuery(topRight).append(topLeft);jQuery(centerRight).append(centerLeft).append(jQuery.NiceJForms.textareas[q]);jQuery(bottomRight).append(bottomLeft);jQuery(container).append(topRight).append(centerRight).append(bottomRight);jQuery(where2).before(container);$(jQuery.NiceJForms.textareas[q]).focus(function(){$(this).prev().removeClass().addClass("cntr_l_xon");$(this).parent().removeClass().addClass("cntr_xon");$(this).parent().prev().removeClass().addClass("tr_xon");$(this).parent().prev().children(".txt_corner").attr('src',jQuery.NiceJForms.options.imagesPath+"txtarea_tl_xon.gif");$(this).parent().next().removeClass().addClass("br_xon");$(this).parent().next().children(".txt_corner").attr('src',jQuery.NiceJForms.options.imagesPath+"txtarea_bl_xon.gif")});$(jQuery.NiceJForms.textareas[q]).blur(function(){$(this).prev().removeClass().addClass("cntr_l");$(this).parent().removeClass().addClass("cntr");$(this).parent().prev().removeClass().addClass("tr");$(this).parent().prev().children(".txt_corner").attr('src',jQuery.NiceJForms.options.imagesPath+"txtarea_tl.gif");$(this).parent().next().removeClass().addClass("br");$(this).parent().next().children(".txt_corner").attr('src',jQuery.NiceJForms.options.imagesPath+"txtarea_bl.gif")});});},buttonHovers:function(){jQuery.NiceJForms.buttons.each(function(i){$(this).addClass("buttonSubmit");var buttonLeft=document.createElement('img');jQuery(buttonLeft).attr({src:jQuery.NiceJForms.options.imagesPath+"button_left.gif"}).addClass("buttonImg");$(this).before(buttonLeft);var buttonRight=document.createElement('img');jQuery(buttonRight).attr({src:jQuery.NiceJForms.options.imagesPath+"button_right.gif"}).addClass("buttonImg");if($(this).next()){$(this).after(buttonRight)}
else{$(this).parent().append(buttonRight)};$(this).hover(function(){$(this).attr("class",$(this).attr("class")+"Hovered");$(this).prev().attr("src",jQuery.NiceJForms.options.imagesPath+"button_left_xon.gif");$(this).next().attr("src",jQuery.NiceJForms.options.imagesPath+"button_right_xon.gif")},function(){$(this).attr("class",$(this).attr("class").replace(/Hovered/g,""));$(this).prev().attr("src",jQuery.NiceJForms.options.imagesPath+"button_left.gif");$(this).next().attr("src",jQuery.NiceJForms.options.imagesPath+"button_right.gif")});});}}
jQuery.NiceJForms={options:{selectRightSideWidth:21,selectLeftSideWidth:8,selectAreaHeight:21,selectAreaOptionsOverlap:2,imagesPath:"css/images/default/"},selectText:'please select',preloads:new Array(),inputs:new Array(),labels:new Array(),textareas:new Array(),selects:new Array(),radios:new Array(),checkboxes:new Array(),texts:new Array(),buttons:new Array(),radioLabels:new Array(),checkboxLabels:new Array(),hasImages:true,keyPressed:function(event)
{var pressedKey=event.charCode||event.keyCode||-1;switch(pressedKey)
{case 40:var fieldId=this.parentNode.parentNode.id.replace(/sarea/g,"");var linkNo=0;for(var q=0;q<selects[fieldId].options.length;q++){if(selects[fieldId].options[q].selected){linkNo=q;}}
++linkNo;if(linkNo>=selects[fieldId].options.length){linkNo=0;}
selectMe(selects[fieldId].id,linkNo,fieldId);break;case 38:var fieldId=this.parentNode.parentNode.id.replace(/sarea/g,"");var linkNo=0;for(var q=0;q<selects[fieldId].options.length;q++){if(selects[fieldId].options[q].selected){linkNo=q;}}
--linkNo;if(linkNo<0){linkNo=selects[fieldId].options.length-1;}
selectMe(selects[fieldId].id,linkNo,fieldId);break;default:break;}},build:function(options)
{if(options)
jQuery.extend(jQuery.NiceJForms.options,options);if(window.event){jQuery('body',document).bind('keyup',jQuery.NiceJForms.keyPressed);}else{jQuery(document).bind('keyup',jQuery.NiceJForms.keyPressed);}
var testImg=document.createElement('img');$(testImg).attr("src",jQuery.NiceJForms.options.imagesPath+"blank.gif").attr("id","imagineTest");jQuery('body').append(testImg);if(testImg.complete)
{if(testImg.offsetWidth=='1'){jQuery.NiceJForms.hasImages=true;}
else{jQuery.NiceJForms.hasImages=false;}}
$(testImg).remove();if(jQuery.NiceJForms.hasImages)
{$('form.niceform').each(function()
{el=jQuery(this);jQuery.NiceJForms.preloadImages();jQuery.NiceJForms.getElements(el);jQuery.NiceJForms.replaceRadios();jQuery.NiceJForms.replaceCheckboxes();jQuery.NiceJForms.replaceSelects();if(!$.browser.safari){jQuery.NiceJForms.replaceTexts();jQuery.NiceJForms.replaceTextareas();jQuery.NiceJForms.buttonHovers();}});}},preloadImages:function()
{jQuery.NiceJForms.preloads=$.preloadImages(jQuery.NiceJForms.options.imagesPath+"button_left_xon.gif",jQuery.NiceJForms.options.imagesPath+"button_right_xon.gif",jQuery.NiceJForms.options.imagesPath+"input_left_xon.gif",jQuery.NiceJForms.options.imagesPath+"input_right_xon.gif",jQuery.NiceJForms.options.imagesPath+"txtarea_bl_xon.gif",jQuery.NiceJForms.options.imagesPath+"txtarea_br_xon.gif",jQuery.NiceJForms.options.imagesPath+"txtarea_cntr_xon.gif",jQuery.NiceJForms.options.imagesPath+"txtarea_l_xon.gif",jQuery.NiceJForms.options.imagesPath+"txtarea_tl_xon.gif",jQuery.NiceJForms.options.imagesPath+"txtarea_tr_xon.gif");},getElements:function(elm)
{el=elm?jQuery(elm):jQuery(this);var r=0;var c=0;var t=0;var rl=0;var cl=0;var tl=0;var b=0;jQuery.NiceJForms.inputs=$('input',el);jQuery.NiceJForms.labels=$('label',el);jQuery.NiceJForms.textareas=$('textarea',el);jQuery.NiceJForms.selects=$('select',el);jQuery.NiceJForms.radios=$('input[@type=radio]',el);jQuery.NiceJForms.checkboxes=$('input[@type=checkbox]',el);jQuery.NiceJForms.texts=$('input[@type=text]',el).add($('input[@type=password]',el));jQuery.NiceJForms.buttons=$('input[@type=submit]',el).add($('input[@type=button]',el));jQuery.NiceJForms.labels.each(function(i){labelFor=$(jQuery.NiceJForms.labels[i]).attr("for");jQuery.NiceJForms.radios.each(function(q){if(labelFor==$(jQuery.NiceJForms.radios[q]).attr("id"))
{if(jQuery.NiceJForms.radios[q].checked)
{$(jQuery.NiceJForms.labels[i]).removeClass().addClass("chosen");}
jQuery.NiceJForms.radioLabels[rl]=jQuery.NiceJForms.labels[i];++rl;}})
jQuery.NiceJForms.checkboxes.each(function(x){if(labelFor==$(this).attr("id"))
{if(this.checked)
{$(jQuery.NiceJForms.labels[i]).removeClass().addClass("chosen");}
jQuery.NiceJForms.checkboxLabels[cl]=jQuery.NiceJForms.labels[i];++cl;}})});},replaceRadios:function()
{var self=this;jQuery.NiceJForms.radios.each(function(q){$(this).removeClass().addClass('outtaHere');var radioArea=document.createElement('div');if(this.checked){$(radioArea).removeClass().addClass("radioAreaChecked");}else{$(radioArea).removeClass().addClass("radioArea");};radioPos=jQuery.iUtil.getPosition(this);jQuery(radioArea).attr({id:'myRadio'+q}).css({left:radioPos.x+'px',top:radioPos.y+'px',margin:'1px'}).bind('click',{who:q},function(e){self.rechangeRadios(e)}).insertBefore($(this));$(jQuery.NiceJForms.radioLabels[q]).bind('click',{who:q},function(e){self.rechangeRadios(e)});if(!$.browser.msie){$(this).bind('focus',function(){self.focusRadios(q)}).bind('blur',function(){self.blurRadios(q)});}
$(this).bind('click',function(e){self.radioEvent(e)});});return true;},changeRadios:function(who){var self=this;if(jQuery.NiceJForms.radios[who].checked){jQuery.NiceJForms.radios.each(function(q){if($(this).attr("name")==$(jQuery.NiceJForms.radios[who]).attr("name"))
{this.checked=false;$(jQuery.NiceJForms.radioLabels[q]).removeClass();}});jQuery.NiceJForms.radios[who].checked=true;$(jQuery.NiceJForms.radioLabels[who]).addClass("chosen");self.checkRadios(who);}},rechangeRadios:function(e)
{who=e.data.who;if(!jQuery.NiceJForms.radios[who].checked){for(var q=0;q<jQuery.NiceJForms.radios.length;q++)
{if(jQuery.NiceJForms.radios[q].name==jQuery.NiceJForms.radios[who].name)
{jQuery.NiceJForms.radios[q].checked=false;jQuery.NiceJForms.radioLabels[q].className="";}}
$(jQuery.NiceJForms.radios[who]).attr('checked',true);jQuery.NiceJForms.radioLabels[who].className="chosen";jQuery.NiceJForms.checkRadios(who);}},checkRadios:function(who){$('div').each(function(q){if($(this).is(".radioAreaChecked")&&$(this).next().attr("name")==$(jQuery.NiceJForms.radios[who]).attr("name")){$(this).removeClass().addClass("radioArea");}});$('#myRadio'+who).toggleClass("radioAreaChecked");},focusRadios:function(who){$('#myRadio'+who).css({border:'1px dotted #333',margin:'0'});return false;},blurRadios:function(who){$('#myRadio'+who).css({border:'none',margin:'1px'});return false;},radioEvent:function(e){var self=this;if(!e)var e=window.event;if(e.type=="click"){for(var q=0;q<jQuery.NiceJForms.radios.length;q++){if(this==jQuery.NiceJForms.radios[q]){self.changeRadios(q);break;}}}},replaceCheckboxes:function()
{var self=this;jQuery.NiceJForms.checkboxes.each(function(q){$(jQuery.NiceJForms.checkboxes[q]).removeClass().addClass('outtaHere');var checkboxArea=document.createElement('div');if(jQuery.NiceJForms.checkboxes[q].checked){$(checkboxArea).removeClass().addClass("checkboxAreaChecked");}else{$(checkboxArea).removeClass().addClass("checkboxArea");};checkboxPos=jQuery.iUtil.getPosition(jQuery.NiceJForms.checkboxes[q]);jQuery(checkboxArea).attr({id:'myCheckbox'+q}).css({left:checkboxPos.x+'px',top:checkboxPos.y+'px',margin:'1px'}).bind('click',{who:q},function(e){self.rechangeCheckboxes(e)}).insertBefore($(jQuery.NiceJForms.checkboxes[q]));if(!$.browser.safari)
{$(jQuery.NiceJForms.checkboxLabels[q]).bind('click',{who:q},function(e){self.changeCheckboxes(e)})}
else{$(jQuery.NiceJForms.checkboxLabels[q]).bind('click',{who:q},function(e){self.rechangeCheckboxes(e)})}
if(!$.browser.msie)
{$(jQuery.NiceJForms.checkboxes[q]).bind('focus',{who:q},function(e){self.focusCheckboxes(e)});$(jQuery.NiceJForms.checkboxes[q]).bind('blur',{who:q},function(e){self.blurCheckboxes(e)});}});return true;},rechangeCheckboxes:function(e)
{who=e.data.who;var tester=false;if($(jQuery.NiceJForms.checkboxLabels[who]).is(".chosen")){tester=false;$(jQuery.NiceJForms.checkboxLabels[who]).removeClass();}
else if(jQuery.NiceJForms.checkboxLabels[who].className==""){tester=true;$(jQuery.NiceJForms.checkboxLabels[who]).addClass("chosen");}
jQuery.NiceJForms.checkboxes[who].checked=tester;jQuery.NiceJForms.checkCheckboxes(who,tester);},checkCheckboxes:function(who,action)
{var what=$('#myCheckbox'+who);if(action==true){$(what).removeClass().addClass("checkboxAreaChecked");}
if(action==false){$(what).removeClass().addClass("checkboxArea");}},focusCheckboxes:function(who)
{var what=$('#myCheckbox'+who);$(what).css({border:"1px dotted #333",margin:"0"});return false;},changeCheckboxes:function(e){who=e.data.who;if($(jQuery.NiceJForms.checkboxLabels[who]).is(".chosen")){jQuery.NiceJForms.checkboxes[who].checked=true;$(jQuery.NiceJForms.checkboxLabels[who]).removeClass();jQuery.NiceJForms.checkCheckboxes(who,false);}
else if(jQuery.NiceJForms.checkboxLabels[who].className==""){jQuery.NiceJForms.checkboxes[who].checked=false;$(jQuery.NiceJForms.checkboxLabels[who]).toggleClass("chosen");jQuery.NiceJForms.checkCheckboxes(who,true);}},blurCheckboxes:function(who)
{var what=$('#myCheckbox'+who);$(what).css({border:'none',margin:'1px'});return false;},replaceSelects:function()
{var self=this;jQuery.NiceJForms.selects.each(function(q){var selectArea=document.createElement('div');var left=document.createElement('div');var right=document.createElement('div');var center=document.createElement('div');var button=document.createElement('a');var text=document.createTextNode(jQuery.NiceJForms.selectText);var selectWidth=parseInt(this.className.replace(/width_/g,""));jQuery(center).attr({id:'mySelectText'+q}).css({width:selectWidth-10+'px'});jQuery(selectArea).attr({id:'sarea'+q}).css({width:selectWidth+jQuery.NiceJForms.options.selectRightSideWidth+jQuery.NiceJForms.options.selectLeftSideWidth+'px'}).addClass("selectArea");jQuery(button).css({width:selectWidth+jQuery.NiceJForms.options.selectRightSideWidth+jQuery.NiceJForms.options.selectLeftSideWidth+'px',marginLeft:-selectWidth-jQuery.NiceJForms.options.selectLeftSideWidth+'px',cursor:'pointer'}).addClass("selectButton").bind('click',{who:q},function(e){self.showOptions(e)}).keydown(jQuery.NiceJForms.keyPressed);jQuery(left).addClass("left");jQuery(right).addClass("right").append(button);jQuery(center).addClass("center").append(text);jQuery(selectArea).append(left).append(right).append(center).insertBefore(this);$(this).hide();var optionsDiv=document.createElement('div');selectAreaPos=jQuery.iUtil.getPosition(selectArea);jQuery(optionsDiv).attr({id:"optionsDiv"+q}).css({width:selectWidth+1+'px',left:selectAreaPos.x+'px',top:selectAreaPos.y+jQuery.NiceJForms.options.selectAreaHeight-jQuery.NiceJForms.options.selectAreaOptionsOverlap+'px'}).addClass("optionsDivInvisible");$(jQuery.NiceJForms.selects[q]).children().each(function(w){var optionHolder=document.createElement('p');var optionLink=document.createElement('a');var optionTxt=document.createTextNode(jQuery.NiceJForms.selects[q].options[w].text);jQuery(optionLink).attr({href:'#'}).css({cursor:'pointer'}).append(optionTxt).bind('click',{who:q,id:jQuery.NiceJForms.selects[q].id,option:w,select:q},function(e){self.showOptions(e);self.selectMe(jQuery.NiceJForms.selects[q].id,w,q)});jQuery(optionHolder).append(optionLink);jQuery(optionsDiv).append(optionHolder);if(jQuery.NiceJForms.selects[q].options[w].selected){self.selectMe($(jQuery.NiceJForms.selects[q]).attr("id"),w,q);}});jQuery('body').append(optionsDiv);});},selectMe:function(selectFieldId,linkNo,selectNo){selectField=$('#'+selectFieldId);sFoptions=selectField.children();selectField.children().each(function(k){if(k==linkNo){sFoptions[k].selected="selected";}
else{sFoptions[k].selected="";}});textVar=$("#mySelectText"+selectNo);var newText=document.createTextNode($(sFoptions[linkNo]).text());textVar.empty().append(newText);},showOptions:function(e){var self=this;$("#optionsDiv"+e.data.who).toggleClass("optionsDivVisible").toggleClass("optionsDivInvisible").mouseout(function(e){self.hideOptions(e)});},hideOptions:function(e){if(!e)var e=window.event;var reltg=(e.relatedTarget)?e.relatedTarget:e.toElement;if(((reltg.nodeName!='A')&&(reltg.nodeName!='DIV'))||((reltg.nodeName=='A')&&(reltg.className=="selectButton")&&(reltg.nodeName!='DIV'))){this.className="optionsDivInvisible";};e.cancelBubble=true;if(e.stopPropagation)e.stopPropagation();},replaceTexts:function(){jQuery.NiceJForms.texts.each(function(q){$(jQuery.NiceJForms.texts[q]).css({width:this.size*10+'px'});var txtLeft=new Image();jQuery(txtLeft).attr({src:jQuery.NiceJForms.options.imagesPath+"input_left.gif"}).addClass("inputCorner");var txtRight=new Image();jQuery(txtRight).attr({src:jQuery.NiceJForms.options.imagesPath+"input_right.gif"}).addClass("inputCorner");$(jQuery.NiceJForms.texts[q]).before(txtLeft).after(txtRight).addClass("textinput");$(jQuery.NiceJForms.texts[q]).focus(function(){$(this).addClass("textinputHovered");$(this).prev().attr('src',jQuery.NiceJForms.options.imagesPath+"input_left_xon.gif");$(this).next().attr('src',jQuery.NiceJForms.options.imagesPath+"input_right_xon.gif");});$(jQuery.NiceJForms.texts[q]).blur(function(){$(this).removeClass().addClass("textinput");$(this).prev().attr('src',jQuery.NiceJForms.options.imagesPath+"input_left.gif");$(this).next().attr('src',jQuery.NiceJForms.options.imagesPath+"input_right.gif");});});},replaceTextareas:function(){jQuery.NiceJForms.textareas.each(function(q){var where=$(this).parent();var where2=$(this).prev();$(this).css({width:$(this).attr("cols")*10+'px',height:$(this).attr("rows")*10+'px'});var container=document.createElement('div');jQuery(container).css({width:jQuery.NiceJForms.textareas[q].cols*10+20+'px',height:jQuery.NiceJForms.textareas[q].rows*10+20+'px'}).addClass("txtarea");var topRight=document.createElement('div');jQuery(topRight).addClass("tr");var topLeft=new Image();jQuery(topLeft).attr({src:jQuery.NiceJForms.options.imagesPath+'txtarea_tl.gif'}).addClass("txt_corner");var centerRight=document.createElement('div');jQuery(centerRight).addClass("cntr");var centerLeft=document.createElement('div');jQuery(centerLeft).addClass("cntr_l");if(!$.browser.msie){jQuery(centerLeft).height(jQuery.NiceJForms.textareas[q].rows*10+10+'px')}
else{jQuery(centerLeft).height(jQuery.NiceJForms.textareas[q].rows*10+12+'px')};var bottomRight=document.createElement('div');jQuery(bottomRight).addClass("br");var bottomLeft=new Image();jQuery(bottomLeft).attr({src:jQuery.NiceJForms.options.imagesPath+'txtarea_bl.gif'}).addClass('txt_corner');jQuery(topRight).append(topLeft);jQuery(centerRight).append(centerLeft).append(jQuery.NiceJForms.textareas[q]);jQuery(bottomRight).append(bottomLeft);jQuery(container).append(topRight).append(centerRight).append(bottomRight);jQuery(where2).before(container);$(jQuery.NiceJForms.textareas[q]).focus(function(){$(this).prev().removeClass().addClass("cntr_l_xon");$(this).parent().removeClass().addClass("cntr_xon");$(this).parent().prev().removeClass().addClass("tr_xon");$(this).parent().prev().children(".txt_corner").attr('src',jQuery.NiceJForms.options.imagesPath+"txtarea_tl_xon.gif");$(this).parent().next().removeClass().addClass("br_xon");$(this).parent().next().children(".txt_corner").attr('src',jQuery.NiceJForms.options.imagesPath+"txtarea_bl_xon.gif")});$(jQuery.NiceJForms.textareas[q]).blur(function(){$(this).prev().removeClass().addClass("cntr_l");$(this).parent().removeClass().addClass("cntr");$(this).parent().prev().removeClass().addClass("tr");$(this).parent().prev().children(".txt_corner").attr('src',jQuery.NiceJForms.options.imagesPath+"txtarea_tl.gif");$(this).parent().next().removeClass().addClass("br");$(this).parent().next().children(".txt_corner").attr('src',jQuery.NiceJForms.options.imagesPath+"txtarea_bl.gif")});});},buttonHovers:function(){jQuery.NiceJForms.buttons.each(function(i){$(this).addClass("buttonSubmit");var buttonLeft=document.createElement('img');jQuery(buttonLeft).attr({src:jQuery.NiceJForms.options.imagesPath+"button_left.gif"}).addClass("buttonImg");$(this).before(buttonLeft);var buttonRight=document.createElement('img');jQuery(buttonRight).attr({src:jQuery.NiceJForms.options.imagesPath+"button_right.gif"}).addClass("buttonImg");if($(this).next()){$(this).after(buttonRight)}
else{$(this).parent().append(buttonRight)};$(this).hover(function(){$(this).attr("class",$(this).attr("class")+"Hovered");$(this).prev().attr("src",jQuery.NiceJForms.options.imagesPath+"button_left_xon.gif");$(this).next().attr("src",jQuery.NiceJForms.options.imagesPath+"button_right_xon.gif")},function(){$(this).attr("class",$(this).attr("class").replace(/Hovered/g,""));$(this).prev().attr("src",jQuery.NiceJForms.options.imagesPath+"button_left.gif");$(this).next().attr("src",jQuery.NiceJForms.options.imagesPath+"button_right.gif")});});}}
jQuery.preloadImages=function()
{var imgs=new Array();for(var i=0;i<arguments.length;i++)
{imgs[i]=jQuery("<img>").attr("src",arguments[i]);}
return imgs;}
jQuery.iUtil={getPosition:function(e)
{var x=0;var y=0;var restoreStyle=false;var es=e.style;if(jQuery(e).css('display')=='none'){oldVisibility=es.visibility;oldPosition=es.position;es.visibility='hidden';es.display='block';es.position='absolute';restoreStyle=true;}
var el=e;while(el){x+=el.offsetLeft+(el.currentStyle&&!jQuery.browser.opera?parseInt(el.currentStyle.borderLeftWidth)||0:0);y+=el.offsetTop+(el.currentStyle&&!jQuery.browser.opera?parseInt(el.currentStyle.borderTopWidth)||0:0);el=el.offsetParent;}
el=e;while(el&&el.tagName&&el.tagName.toLowerCase()!='body')
{x-=el.scrollLeft||0;y-=el.scrollTop||0;el=el.parentNode;}
if(restoreStyle){es.display='none';es.position=oldPosition;es.visibility=oldVisibility;}
return{x:x,y:y};},getPositionLite:function(el)
{var x=0,y=0;while(el){x+=el.offsetLeft||0;y+=el.offsetTop||0;el=el.offsetParent;}
return{x:x,y:y};}};
(function($){$.fn.lightBox=function(settings){settings=jQuery.extend({overlayBgColor:'#000',overlayOpacity:0.8,fixedNavigation:false,imageLoading:'images/lightbox-ico-loading.gif',imageBtnPrev:'images/lightbox-btn-prev.gif',imageBtnNext:'images/lightbox-btn-next.gif',imageBtnClose:'images/lightbox-btn-close.gif',imageBlank:'images/lightbox-blank.gif',containerBorderSize:10,containerResizeSpeed:400,txtImage:'Image',txtOf:'of',keyToClose:'c',keyToPrev:'p',keyToNext:'n',imageArray:[],activeImage:0},settings);var jQueryMatchedObj=this;function _initialize(){_start(this,jQueryMatchedObj);return false;}
function _start(objClicked,jQueryMatchedObj){$('embed, object, select').css({'visibility':'hidden'});_set_interface();settings.imageArray.length=0;settings.activeImage=0;if(jQueryMatchedObj.length==1){settings.imageArray.push(new Array(objClicked.getAttribute('href'),objClicked.getAttribute('title')));}else{for(var i=0;i<jQueryMatchedObj.length;i++){settings.imageArray.push(new Array(jQueryMatchedObj[i].getAttribute('href'),jQueryMatchedObj[i].getAttribute('title')));}}
while(settings.imageArray[settings.activeImage][0]!=objClicked.getAttribute('href')){settings.activeImage++;}
_set_image_to_view();}
function _set_interface(){$('body').append('<div id="jquery-overlay"></div><div id="jquery-lightbox"><div id="lightbox-container-image-box"><div id="lightbox-container-image"><img id="lightbox-image"><div style="" id="lightbox-nav"><a href="#" id="lightbox-nav-btnPrev"></a><a href="#" id="lightbox-nav-btnNext"></a></div><div id="lightbox-loading"><a href="#" id="lightbox-loading-link"><img src="'+settings.imageLoading+'"></a></div></div></div><div id="lightbox-container-image-data-box"><div id="lightbox-container-image-data"><div id="lightbox-image-details"><span id="lightbox-image-details-caption"></span><span id="lightbox-image-details-currentNumber"></span></div><div id="lightbox-secNav"><a href="#" id="lightbox-secNav-btnClose"><img src="'+settings.imageBtnClose+'"></a></div></div></div></div>');var arrPageSizes=___getPageSize();$('#jquery-overlay').css({backgroundColor:settings.overlayBgColor,opacity:settings.overlayOpacity,width:arrPageSizes[0],height:arrPageSizes[1]}).fadeIn();var arrPageScroll=___getPageScroll();$('#jquery-lightbox').css({top:arrPageScroll[1]+(arrPageSizes[3]/10),left:arrPageScroll[0]}).show();$('#jquery-overlay,#jquery-lightbox').click(function(){_finish();});$('#lightbox-loading-link,#lightbox-secNav-btnClose').click(function(){_finish();return false;});$(window).resize(function(){var arrPageSizes=___getPageSize();$('#jquery-overlay').css({width:arrPageSizes[0],height:arrPageSizes[1]});var arrPageScroll=___getPageScroll();$('#jquery-lightbox').css({top:arrPageScroll[1]+(arrPageSizes[3]/10),left:arrPageScroll[0]});});}
function _set_image_to_view(){$('#lightbox-loading').show();if(settings.fixedNavigation){$('#lightbox-image,#lightbox-container-image-data-box,#lightbox-image-details-currentNumber').hide();}else{$('#lightbox-image,#lightbox-nav,#lightbox-nav-btnPrev,#lightbox-nav-btnNext,#lightbox-container-image-data-box,#lightbox-image-details-currentNumber').hide();}
var objImagePreloader=new Image();objImagePreloader.onload=function(){$('#lightbox-image').attr('src',settings.imageArray[settings.activeImage][0]);_resize_container_image_box(objImagePreloader.width,objImagePreloader.height);objImagePreloader.onload=function(){};};objImagePreloader.src=settings.imageArray[settings.activeImage][0];};function _resize_container_image_box(intImageWidth,intImageHeight){var intCurrentWidth=$('#lightbox-container-image-box').width();var intCurrentHeight=$('#lightbox-container-image-box').height();var intWidth=(intImageWidth+(settings.containerBorderSize*2));var intHeight=(intImageHeight+(settings.containerBorderSize*2));var intDiffW=intCurrentWidth-intWidth;var intDiffH=intCurrentHeight-intHeight;$('#lightbox-container-image-box').animate({width:intWidth,height:intHeight},settings.containerResizeSpeed,function(){_show_image();});if((intDiffW==0)&&(intDiffH==0)){if($.browser.msie){___pause(250);}else{___pause(100);}}
$('#lightbox-container-image-data-box').css({width:intImageWidth});$('#lightbox-nav-btnPrev,#lightbox-nav-btnNext').css({height:intImageHeight+(settings.containerBorderSize*2)});};function _show_image(){$('#lightbox-loading').hide();$('#lightbox-image').fadeIn(function(){_show_image_data();_set_navigation();});_preload_neighbor_images();};function _show_image_data(){$('#lightbox-container-image-data-box').slideDown('fast');$('#lightbox-image-details-caption').hide();if(settings.imageArray[settings.activeImage][1]){$('#lightbox-image-details-caption').html(settings.imageArray[settings.activeImage][1]).show();}
if(settings.imageArray.length>1){$('#lightbox-image-details-currentNumber').html(settings.txtImage+' '+(settings.activeImage+1)+' '+settings.txtOf+' '+settings.imageArray.length).show();}}
function _set_navigation(){$('#lightbox-nav').show();$('#lightbox-nav-btnPrev,#lightbox-nav-btnNext').css({'background':'transparent url('+settings.imageBlank+') no-repeat'});if(settings.activeImage!=0){if(settings.fixedNavigation){$('#lightbox-nav-btnPrev').css({'background':'url('+settings.imageBtnPrev+') left 15% no-repeat'}).unbind().bind('click',function(){settings.activeImage=settings.activeImage-1;_set_image_to_view();return false;});}else{$('#lightbox-nav-btnPrev').unbind().hover(function(){$(this).css({'background':'url('+settings.imageBtnPrev+') left 15% no-repeat'});},function(){$(this).css({'background':'transparent url('+settings.imageBlank+') no-repeat'});}).show().bind('click',function(){settings.activeImage=settings.activeImage-1;_set_image_to_view();return false;});}}
if(settings.activeImage!=(settings.imageArray.length-1)){if(settings.fixedNavigation){$('#lightbox-nav-btnNext').css({'background':'url('+settings.imageBtnNext+') right 15% no-repeat'}).unbind().bind('click',function(){settings.activeImage=settings.activeImage+1;_set_image_to_view();return false;});}else{$('#lightbox-nav-btnNext').unbind().hover(function(){$(this).css({'background':'url('+settings.imageBtnNext+') right 15% no-repeat'});},function(){$(this).css({'background':'transparent url('+settings.imageBlank+') no-repeat'});}).show().bind('click',function(){settings.activeImage=settings.activeImage+1;_set_image_to_view();return false;});}}
_enable_keyboard_navigation();}
function _enable_keyboard_navigation(){$(document).keydown(function(objEvent){_keyboard_action(objEvent);});}
function _disable_keyboard_navigation(){$(document).unbind();}
function _keyboard_action(objEvent){if(objEvent==null){keycode=event.keyCode;escapeKey=27;}else{keycode=objEvent.keyCode;escapeKey=objEvent.DOM_VK_ESCAPE;}
key=String.fromCharCode(keycode).toLowerCase();if((key==settings.keyToClose)||(key=='x')||(keycode==escapeKey)){_finish();}
if((key==settings.keyToPrev)||(keycode==37)){if(settings.activeImage!=0){settings.activeImage=settings.activeImage-1;_set_image_to_view();_disable_keyboard_navigation();}}
if((key==settings.keyToNext)||(keycode==39)){if(settings.activeImage!=(settings.imageArray.length-1)){settings.activeImage=settings.activeImage+1;_set_image_to_view();_disable_keyboard_navigation();}}}
function _preload_neighbor_images(){if((settings.imageArray.length-1)>settings.activeImage){objNext=new Image();objNext.src=settings.imageArray[settings.activeImage+1][0];}
if(settings.activeImage>0){objPrev=new Image();objPrev.src=settings.imageArray[settings.activeImage-1][0];}}
function _finish(){$('#jquery-lightbox').remove();$('#jquery-overlay').fadeOut(function(){$('#jquery-overlay').remove();});$('embed, object, select').css({'visibility':'visible'});}
function ___getPageSize(){var xScroll,yScroll;if(window.innerHeight&&window.scrollMaxY){xScroll=window.innerWidth+window.scrollMaxX;yScroll=window.innerHeight+window.scrollMaxY;}else if(document.body.scrollHeight>document.body.offsetHeight){xScroll=document.body.scrollWidth;yScroll=document.body.scrollHeight;}else{xScroll=document.body.offsetWidth;yScroll=document.body.offsetHeight;}
var windowWidth,windowHeight;if(self.innerHeight){if(document.documentElement.clientWidth){windowWidth=document.documentElement.clientWidth;}else{windowWidth=self.innerWidth;}
windowHeight=self.innerHeight;}else if(document.documentElement&&document.documentElement.clientHeight){windowWidth=document.documentElement.clientWidth;windowHeight=document.documentElement.clientHeight;}else if(document.body){windowWidth=document.body.clientWidth;windowHeight=document.body.clientHeight;}
if(yScroll<windowHeight){pageHeight=windowHeight;}else{pageHeight=yScroll;}
if(xScroll<windowWidth){pageWidth=xScroll;}else{pageWidth=windowWidth;}
arrayPageSize=new Array(pageWidth,pageHeight,windowWidth,windowHeight);return arrayPageSize;};function ___getPageScroll(){var xScroll,yScroll;if(self.pageYOffset){yScroll=self.pageYOffset;xScroll=self.pageXOffset;}else if(document.documentElement&&document.documentElement.scrollTop){yScroll=document.documentElement.scrollTop;xScroll=document.documentElement.scrollLeft;}else if(document.body){yScroll=document.body.scrollTop;xScroll=document.body.scrollLeft;}
arrayPageScroll=new Array(xScroll,yScroll);return arrayPageScroll;};function ___pause(ms){var date=new Date();curDate=null;do{var curDate=new Date();}
while(curDate-date<ms);};return this.unbind('click').click(_initialize);};})(jQuery);