package com.throne212.fupin.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "smsServicePortType", targetNamespace = "www.kwhope.com")
public interface SmsServicePortType {

	/**
	 * 
	 * @param in7
	 * @param in2
	 * @param in0
	 * @param in4
	 * @param in8
	 * @param in6
	 * @param in1
	 * @param in5
	 * @param in3
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "www.kwhope.com")
	@RequestWrapper(localName = "sendMessageToUser", targetNamespace = "www.kwhope.com", className = "com.throne212.fupin.sms.SendMessageToUser")
	@ResponseWrapper(localName = "sendMessageToUserResponse", targetNamespace = "www.kwhope.com", className = "com.throne212.fupin.sms.SendMessageToUserResponse")
	public int sendMessageToUser(@WebParam(name = "in0", targetNamespace = "www.kwhope.com")
	String in0, @WebParam(name = "in1", targetNamespace = "www.kwhope.com")
	String in1, @WebParam(name = "in2", targetNamespace = "www.kwhope.com")
	String in2, @WebParam(name = "in3", targetNamespace = "www.kwhope.com")
	String in3, @WebParam(name = "in4", targetNamespace = "www.kwhope.com")
	String in4, @WebParam(name = "in5", targetNamespace = "www.kwhope.com")
	String in5, @WebParam(name = "in6", targetNamespace = "www.kwhope.com")
	String in6, @WebParam(name = "in7", targetNamespace = "www.kwhope.com")
	String in7, @WebParam(name = "in8", targetNamespace = "www.kwhope.com")
	int in8);

	/**
	 * 
	 * @param in7
	 * @param in2
	 * @param in0
	 * @param in4
	 * @param in8
	 * @param in6
	 * @param in1
	 * @param in5
	 * @param in3
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "www.kwhope.com")
	@RequestWrapper(localName = "sendMessageToMobile", targetNamespace = "www.kwhope.com", className = "com.throne212.fupin.sms.SendMessageToMobile")
	@ResponseWrapper(localName = "sendMessageToMobileResponse", targetNamespace = "www.kwhope.com", className = "com.throne212.fupin.sms.SendMessageToMobileResponse")
	public int sendMessageToMobile(@WebParam(name = "in0", targetNamespace = "www.kwhope.com")
	String in0, @WebParam(name = "in1", targetNamespace = "www.kwhope.com")
	String in1, @WebParam(name = "in2", targetNamespace = "www.kwhope.com")
	String in2, @WebParam(name = "in3", targetNamespace = "www.kwhope.com")
	String in3, @WebParam(name = "in4", targetNamespace = "www.kwhope.com")
	String in4, @WebParam(name = "in5", targetNamespace = "www.kwhope.com")
	String in5, @WebParam(name = "in6", targetNamespace = "www.kwhope.com")
	String in6, @WebParam(name = "in7", targetNamespace = "www.kwhope.com")
	String in7, @WebParam(name = "in8", targetNamespace = "www.kwhope.com")
	int in8);

}
