document.writeln("           <tr>");
document.writeln("           <td><font class=\'fGreen f14\'>招聘<\/font><\/td>");
document.writeln("           <td ><a href=\'http:\/\/www.jianzhi8.com\/zhiding.html\' target=\'_blank\' ><img alt=\'置顶\' border=0 align=\'absmiddle\' style=\'padding-right:4px;\'  src=\'\/jz8_images\/icoDing.png\'\/><\/a><a  href=\'\/a57202.html\' title=\'因各高层、港 澳 台等顾客娱乐需求,特此招聘以下人员，匀可【兼职】");
document.writeln("1 [男 女 公 关]各30名:要求形象好,具有亲和力");
document.writeln("2 KTV 高级服务员:男\/女 形象好口才佳。沟通能力强,性格活泼开朗,...\' target=\'_blank\'><font color=\'#0033CC\'>大型酒店诚聘专兼职男女KTV服务生（非中介）<\/font><\/a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
document.writeln("           <td >不限<\/td>");
document.writeln("           <td >300-1500元\/天<\/td>");
document.writeln("           <td ><a  target=\'_blank\' class=\'titlerblue greyLink\' href=\'http:\/\/www.jianzhi8.com\/zhiding.html\'>推广...<\/a><\/td>");
document.writeln("         <\/tr>");
document.writeln("    ");
document.writeln("               <tr>");
document.writeln("           <td><font class=\'fGreen f14\'>招聘<\/font><\/td>");
document.writeln("           <td ><a href=\'http:\/\/www.jianzhi8.com\/zhiding.html\' target=\'_blank\' ><img alt=\'置顶\' border=0 align=\'absmiddle\' style=\'padding-right:4px;\'  src=\'\/jz8_images\/icoDing.png\'\/><\/a><a  href=\'\/a308748.html\' title=\'因各高层、港 澳 台等顾客娱乐需求,特此招聘以下人员，匀可【兼职】1 [男 女 公 关]各25名:要求形象好,具有亲和力2 KTV 高级服务员:");
document.writeln("★★：男女公关各20名：...\' target=\'_blank\'><font color=\'#0033CC\'>本酒店长期招聘男女高级服务生公关商务陪同非中介<\/font><\/a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<\/td>");
document.writeln("           <td >不限<\/td>");
document.writeln("           <td >工资300\/1500<\/td>");
document.writeln("           <td ><a  target=\'_blank\' class=\'titlerblue greyLink\' href=\'http:\/\/www.jianzhi8.com\/zhiding.html\'>推广...<\/a><\/td>");
document.writeln("         <\/tr>");

document.writeln("               <tr>");
document.writeln("           <td><font class=\'fGreen f14\'>招聘<\/font><\/td>");
document.writeln("           <td ><a href=\'http:\/\/www.jianzhi8.com\/zhiding.html\' target=\'_blank\' ><img alt=\'置顶\' border=0 align=\'absmiddle\' style=\'padding-right:4px;\'  src=\'\/jz8_images\/icoDing.png\'\/><\/a><a  href=\'\/a200574.html\' title=\'本酒店现因业务需求面向全社会诚聘：");
document.writeln("");
document.writeln("★★：1男女公关（20名）：日薪1500元以上，要求：18－35岁，形象好，气质佳，普通话标准，思想开放大胆，应变能力强，有良好的敬业精神，青春靓丽，时尚前卫...\' target=\'_blank\'><font color=\'#0033CC\'>星级酒店高薪\/直聘\/专兼职\/金牌男女公关高薪服务生<\/font><\/a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<\/td>");
document.writeln("           <td >不限<\/td>");
document.writeln("           <td >1500-3000\/天<\/td>");
document.writeln("           <td ><a  target=\'_blank\' class=\'titlerblue greyLink\' href=\'http:\/\/www.jianzhi8.com\/zhiding.html\'>推广...<\/a><\/td>");
document.writeln("         <\/tr>");
document.writeln("    ");
